// <auto-generated />
using System;
using AllowanceManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AllowanceManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllowanceManagement.Models.CategoryPercentage", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("CategoryId");

                    b.ToTable("CategoryPercentages");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Category = "Α",
                            Description = "100% του αρχικού ποσού για στελέχη με κύρια τοποθέτηση σε Φ/Γ, Υ/Β, Τ/ΠΚ και Κ/Φ",
                            Percentage = 1.00m
                        },
                        new
                        {
                            CategoryId = 2,
                            Category = "Β",
                            Description = "85% του αρχικού ποσού για στελέχη με κύρια τοποθέτηση σε Α/Γ, ΠΓΥ, Ν/ΘΗ και ΠΠ",
                            Percentage = 0.85m
                        },
                        new
                        {
                            CategoryId = 3,
                            Category = "Γ",
                            Description = "70% του αρχικού ποσού για στελέχη με κύρια τοποθέτηση σε ΠΤΜ, ΣΑΠ, Π/Φ, Υ/Φ, Υ/Γ, Υ/Γ-Ω/Κ και ΠΑΤ.",
                            Percentage = 0.70m
                        },
                        new
                        {
                            CategoryId = 4,
                            Category = "Δ",
                            Description = "50% του αρχικού ποσού σε στελέχη με κύρια τοποθέτηση στη Διεύθυνση ΑΣ/ΔΕΠΑ",
                            Percentage = 0.50m
                        });
                });

            modelBuilder.Entity("AllowanceManagement.Models.Employee", b =>
                {
                    b.Property<string>("AM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RankAmountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("SeaDay")
                        .HasColumnType("int");

                    b.HasKey("AM");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RankAmountId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AllowanceManagement.Models.RankAmount", b =>
                {
                    b.Property<int>("RankAmountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RankAmountId"));

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Duty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RankAmountId");

                    b.ToTable("RankAmounts");

                    b.HasData(
                        new
                        {
                            RankAmountId = 1,
                            BaseAmount = 1015.00m,
                            Duty = "Κυβερνήτης",
                            Rank = "Πλοίαρχος"
                        },
                        new
                        {
                            RankAmountId = 2,
                            BaseAmount = 1015.00m,
                            Duty = "Κυβερνήτης",
                            Rank = "Αντιπλοίαρχος"
                        },
                        new
                        {
                            RankAmountId = 3,
                            BaseAmount = 1015.00m,
                            Duty = "-",
                            Rank = "Διευθυντής ΑΣ/ΔΕΠΑ"
                        },
                        new
                        {
                            RankAmountId = 4,
                            BaseAmount = 765.00m,
                            Duty = "Κυβερνήτης",
                            Rank = "Πλωτάρχης"
                        },
                        new
                        {
                            RankAmountId = 5,
                            BaseAmount = 600.00m,
                            Duty = "Κυβερνήτης",
                            Rank = "Υποπλοίαρχος"
                        },
                        new
                        {
                            RankAmountId = 6,
                            BaseAmount = 600.00m,
                            Duty = "Κυβερνήτης",
                            Rank = "Ανθυποπλοίαρχος"
                        },
                        new
                        {
                            RankAmountId = 7,
                            BaseAmount = 600.00m,
                            Duty = "Κυβερνήτης",
                            Rank = "Σημαιοφόρος"
                        },
                        new
                        {
                            RankAmountId = 8,
                            BaseAmount = 670.00m,
                            Duty = "Υ/Αος",
                            Rank = "Αντιπλοίαρχος"
                        },
                        new
                        {
                            RankAmountId = 9,
                            BaseAmount = 670.00m,
                            Duty = "Υ/Αος",
                            Rank = "Πλωτάρχης"
                        },
                        new
                        {
                            RankAmountId = 10,
                            BaseAmount = 600.00m,
                            Duty = "-",
                            Rank = "Αντιπλοίαρχος"
                        },
                        new
                        {
                            RankAmountId = 11,
                            BaseAmount = 600.00m,
                            Duty = "-",
                            Rank = "Πλωτάρχης"
                        },
                        new
                        {
                            RankAmountId = 12,
                            BaseAmount = 535.00m,
                            Duty = "-",
                            Rank = "Υποπλοίαρχος"
                        },
                        new
                        {
                            RankAmountId = 13,
                            BaseAmount = 535.00m,
                            Duty = "-",
                            Rank = "Ανθυποπλοίαρχος"
                        },
                        new
                        {
                            RankAmountId = 14,
                            BaseAmount = 510.00m,
                            Duty = "-",
                            Rank = "Σημαιοφόρος"
                        },
                        new
                        {
                            RankAmountId = 15,
                            BaseAmount = 510.00m,
                            Duty = "-",
                            Rank = "Ανθυπασπιστής"
                        },
                        new
                        {
                            RankAmountId = 16,
                            BaseAmount = 470.00m,
                            Duty = "-",
                            Rank = "Αρχικελευστής"
                        },
                        new
                        {
                            RankAmountId = 17,
                            BaseAmount = 440.00m,
                            Duty = "-",
                            Rank = "Επικελευστής"
                        },
                        new
                        {
                            RankAmountId = 18,
                            BaseAmount = 400.00m,
                            Duty = "-",
                            Rank = "Κελευστής"
                        },
                        new
                        {
                            RankAmountId = 19,
                            BaseAmount = 400.00m,
                            Duty = "-",
                            Rank = "Δίοπος"
                        },
                        new
                        {
                            RankAmountId = 20,
                            BaseAmount = 385.00m,
                            Duty = "-",
                            Rank = "ΕΠΟΠ Ναύτης"
                        },
                        new
                        {
                            RankAmountId = 21,
                            BaseAmount = 385.00m,
                            Duty = "-",
                            Rank = "ΟΒΑ"
                        });
                });

            modelBuilder.Entity("AllowanceManagement.Models.UploadedFile", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FileId");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AllowanceManagement.Models.Employee", b =>
                {
                    b.HasOne("AllowanceManagement.Models.CategoryPercentage", "CategoryPercentage")
                        .WithMany("Employees")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AllowanceManagement.Models.RankAmount", "RankAmount")
                        .WithMany("Employees")
                        .HasForeignKey("RankAmountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryPercentage");

                    b.Navigation("RankAmount");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AllowanceManagement.Models.CategoryPercentage", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AllowanceManagement.Models.RankAmount", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
